import Link from "next/link";
import Footer from "@/components/Footer";

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-10">
      <h2 className="text-lg font-semibold text-white mb-3">{title}</h2>
      <div className="space-y-3 text-sm text-gray-300 leading-relaxed">{children}</div>
    </section>
  );
}

export default function RiskPage() {
  return (
    <main className="min-h-screen pt-14 bg-[#030712]">
      <div className="max-w-2xl mx-auto px-4 py-12">
        <h1 className="text-3xl font-bold text-white mb-2">Risk Disclosure</h1>
        <p className="text-sm text-gray-500 mb-8">Please read this carefully before using Tennis Trader AI</p>

        {/* Warning box */}
        <div className="bg-red-500/5 border border-red-500/20 rounded-2xl p-6 mb-10">
          <div className="flex gap-3">
            <svg className="w-6 h-6 text-red-400 shrink-0 mt-0.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126zM12 15.75h.007v.008H12v-.008z" />
            </svg>
            <div>
              <p className="text-red-300 font-bold text-base mb-2">
                Trading on Betfair Exchange involves significant risk of loss.
              </p>
              <p className="text-red-300/80 text-sm leading-relaxed">
                You should only trade with money you can afford to lose. Do not trade with borrowed
                funds or money required for essential expenses. If you are unsure whether exchange
                trading is appropriate for you, seek independent professional advice.
              </p>
            </div>
          </div>
        </div>

        <Section title="1. Nature of Exchange Trading">
          <p>
            Betfair Exchange is a peer-to-peer betting exchange where you trade against other users,
            not against the house. Prices fluctuate based on market supply and demand, and positions
            can move against you rapidly.
          </p>
          <p>
            When you place a lay bet, your potential liability exceeds your stake. You must ensure you
            understand the mechanics of both backing and laying before trading.
          </p>
          <p>
            Markets can be volatile, especially during live sporting events. Prices may gap
            significantly between ticks, and liquidity may dry up at critical moments.
          </p>
        </Section>

        <Section title="2. No Guarantee of Profit">
          <p>
            Tennis Trader AI does not guarantee any profits. The tools, analysis, and AI signals
            provided are designed to assist your decision-making, but they cannot predict the future
            with certainty.
          </p>
          <p>
            Even with the best tools and analysis, trading involves inherent uncertainty. You may
            experience extended periods of losses. No trading system, strategy, or AI model can
            eliminate the risk of loss.
          </p>
        </Section>

        <Section title="3. AI Signals Disclaimer">
          <p>
            AI-powered signals and analysis provided by Tennis Trader AI are generated by artificial
            intelligence models (Anthropic Claude). These signals represent the AI&apos;s assessment based
            on available data and should be treated as one input among many in your decision-making.
          </p>
          <p>
            AI signals are <span className="text-white font-medium">not financial advice</span>. They
            may be inaccurate, delayed, or based on incomplete information. The AI does not have
            access to real-time injury news, weather conditions, player mental state, or other factors
            that may significantly affect match outcomes.
          </p>
          <p>
            You should never blindly follow AI signals. Always apply your own judgement and risk
            management before placing any trade.
          </p>
        </Section>

        <Section title="4. Past Performance">
          <p>
            Past performance of AI signals, trading strategies, or any analysis provided by Tennis
            Trader AI is not indicative of future results. Historical win rates, profit figures, and
            other statistics are provided for informational purposes only.
          </p>
          <p>
            Market conditions change over time. A strategy or signal type that has been profitable in
            the past may not continue to be profitable in the future.
          </p>
        </Section>

        <Section title="5. Responsible Trading">
          <p>We strongly encourage responsible trading practices:</p>
          <ul className="list-disc list-inside space-y-1.5 text-gray-300 ml-1">
            <li>Set and stick to daily loss limits</li>
            <li>Never chase losses by increasing stake sizes</li>
            <li>Take regular breaks from trading</li>
            <li>Use the AI Guardian and risk management tools provided</li>
            <li>Keep a trading journal and review your performance regularly</li>
            <li>Never trade under the influence of alcohol or when emotionally distressed</li>
          </ul>
          <p>
            If you feel that your trading is becoming a problem, please contact{" "}
            <a href="https://www.begambleaware.org" target="_blank" rel="noopener noreferrer" className="text-blue-400 hover:text-blue-300 transition-colors">
              BeGambleAware.org
            </a>{" "}
            or call the National Gambling Helpline on 0808 8020 133.
          </p>
        </Section>

        <Section title="6. Seek Professional Advice">
          <p>
            If you are unsure about any aspect of exchange trading, the risks involved, or whether
            trading is appropriate for your financial situation, you should seek independent
            professional financial advice before using Tennis Trader AI.
          </p>
          <p>
            Tennis Trader AI and its operators are not financial advisers and are not regulated by the
            Financial Conduct Authority (FCA) for the provision of financial advice.
          </p>
        </Section>

      </div>
      <Footer />
    </main>
  );
}
